Jellof rice recipe
Fidelta/odin-recipes pull request #1
Opened 2023-06-08 16:51 UTC by Fidelta

I create three recipes of Jellof rice, Beans porridge and Egg sauce. I also add the images of these three dishes and created links to their pages.

2023-06-09 01:05 UTC, antoHero commented on Recipes/Beans.html
> +~<!DOCTYPE html>
this symbol ~ on line 1 shows on your page and you do not need it

2023-06-09 01:17 UTC, antoHero requested changes
Good job so far Precious 🔥, I am proud to see your first project. I noticed a few things you need to fix
- when naming your files, you cannot have spaces (eg egg sauce.html). I suggest you call the file eggsauce.html, egg_sauce.html, or egg-sauce.html. Do the same with jellof rice and your images too. After renaming the files, remember to update the links in index.html
- the image on jellof rice recipe page is broken (it doesn't show) because you added a dot when you were linking it on the page. Kindly check and fix that as well
- your images can only have one extension eg .jpg instead of .jpg.jpg you used. Could you remove the extra .jpg and you are good to go? Don't forget to update the way you are linking the images on each recipe page
- finally, you have 3 recipe pages but only 2 are active, abi you no want make we learn how to cook egg? 😉

A few modifications left and your first project will be live 🚀🚀

2023-06-13 10:30 UTC, Kadunapikin requested changes
Good job Precious, you did well on your first project!  However, make necessary correction on line 1 of Beans.html and also rename your html pages using the Camel casing naming convention.

2023-06-14 15:14 UTC, antoHero commented
Congratulations @Fidelta on finishing your first project. We are happy to see you are making progress and have basic  knowledge in
- HTML, and
- git

Before we/you merge your work, consider renaming your images and HTML files using camel case as suggested by @Kadunapikin. Start renaming your folders also with a small case

`eg rename BeansPorridge.jpg to beansPorridge.jpg`

2023-06-14 20:23 UTC, antoHero approved these changes

2023-06-14 22:34 UTC, Kadunapikin approved these changes
Great job and congratulations @Fidelta  on completing your first project! You can go ahead and now merge. Happy coding!!!

2023-06-15 07:22 UTC, merged

2023-06-15 07:24 UTC, Fidelta commented
Well, it's my first project ever and I am excited practicing as I am learning. I wont give up until i get to the desired destination.